[editor]
title = "Bevy Shooter Tools Level Editor"

[viewport]
free = "Freecam"
front = "Front"
top = "Top"
right = "Right"
ui = "UI Camera"

[debug.viewport]
title = "Multicam Viewport"
controls = "Squish Controls"
start = "Start"
end = "End"

[debug.viewport.draw]
title = "Draw Debug Indicators"
mouse = "Mouse Circle"
box = "Viewport Box"
mouseover = "Mouseover Boxes"
probe = "Mouse Probe"

[debug.movement]
title = "Camera Movement"
perspective.title = "Perspective Camera Settings"
perspective.pan = "Perspective camera pan factor"
perspective.rotate = "Perspective camera rotate factor"
perspective.speed = "Perspective camera speed"

[tools]
title = "Tools"
select = "Select"
move = "Move"
room = "Room"

[room.messages]
ghost = "Room { me } is fully inside { other } and will not appear!"
